(lang dune 3.16)

(name microcluster_exec)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name microcluster_exec)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends alcotest re fpath jsont bytesrw ppx_fields_conv eio eio_main fs_socket ocaml pyre-ast opine cmdliner ppx-jsont offshr-code+py ppx_ftor)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
